[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_BASE_URL = "https://tinyhosts.netlify.app"
  NODE_ENV = "production"
  NPM_FLAGS = "--legacy-peer-deps"

# Redirect for GitHub OAuth callback
[[redirects]]
  from = "/api/auth/github/callback"
  to = "/api/auth/github/callback"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/google/callback"
  to = "/api/auth/google/callback"
  status = 200
  force = true
